bancolombia/async-dataflow

.github/workflows/release.yml
Append github action to deploy the image in docker hub.
=> Create Github Action

clients/client-dart/lib/adf_client.dart, clients/client-dart/lib/src/async_client.dart, clients/client-dart/lib/src/async_config.dart, clients/client-dart/lib/src/binary_decoder.dart, clients/client-dart/lib/src/channel_message.dart, clients/client-dart/lib/src/json_decoder.dart, clients/client-dart/lib/src/retry_timer.dart, clients/client-dart/lib/src/transport.dart, clients/client-dart/lib/src/utils.dart, clients/client-dart/pubspec.yaml, clients/client-dart/test/async_client_test.dart, clients/client-dart/test/binary_decoder_test.dart, clients/client-dart/test/json_decoder_test.dart
=> fix(client-dart): refactor and fix

channel-sender/Dockerfile, channel-sender/lib/channel_sender_ex/transport/rest/rest_controller.ex, channel-sender/mix.exs
=> add health endpoint

clients/client-dart/lib/src/json_decoder.dart, clients/client-dart/test/json_decoder_test.dart
=> Simplify json decoder.

clients/client-js/package.json
Rename the library to have the organization
=> append organization

clients/client-js/README.md, clients/client-js/package-lock.json, examples/front-async-angular/package-lock.json, examples/front-async-angular/package.json, examples/front-async-angular/src/app/services/async-client.service.ts
Update example angular using scoped library
=> Update example angular

.github/workflows/release.yml, .github/workflows/secret-scanner.yml, SECURITY.md
Fix vulnerabilities reported in security scanning alerts and activate secret scanner in this repository
=> Fix vulnerability alerts and activate secret scanner

clients/backend-client-elixir/.github/workflows/main.yml, clients/backend-client-elixir/README.md, clients/backend-client-elixir/bench/deliver_message.exs, clients/backend-client-elixir/bench/register_channels.exs, clients/backend-client-elixir/lib/adf_sender_connector.ex, clients/backend-client-elixir/lib/adf_sender_connector/channel.ex, clients/backend-client-elixir/lib/adf_sender_connector/message.ex, clients/backend-client-elixir/lib/adf_sender_connector/router.ex, clients/backend-client-elixir/lib/adf_sender_connector/spec.ex, clients/backend-client-elixir/mix.exs, clients/backend-client-elixir/mix.lock, clients/backend-client-elixir/test/adf_sender_connector/channel_test.exs, clients/backend-client-elixir/test/adf_sender_connector/router_test.exs, clients/backend-client-elixir/test/adf_sender_connector/spec_test.exs, clients/backend-client-elixir/test/adf_sender_connector_test.exs
feat!: Api changes in AdfSenderConnector module to make it easy to use and improve performance in requesting to send messages.
This change is a pre-requisite to solve #37.
=> Api changes in AdfSenderConnector module

.github/workflows/backend-client-elixir.yaml
Setup action for sender elixirs client CI/RM
=> set action workflow folder

clients/backend-client-elixir/README.md, clients/backend-client-elixir/lib/adf_sender_connector.ex, clients/backend-client-elixir/lib/adf_sender_connector/spec.ex, clients/backend-client-elixir/test/adf_sender_connector/channel_test.exs, clients/backend-client-elixir/test/adf_sender_connector/router_test.exs, clients/backend-client-elixir/test/adf_sender_connector/spec_test.exs, clients/backend-client-elixir/test/adf_sender_connector_test.exs
Update client configuration mechanism, via the child spec definition.
=> feat: elixir client modification

.github/workflows/release-client-dart.yml, .vscode/launch.json, clients/client-dart/CHANGELOG.md, clients/client-dart/analysis_options.yaml, clients/client-dart/example/adf_client_example.dart, clients/client-dart/lib/src/async_client.dart, clients/client-dart/lib/src/async_config.dart, clients/client-dart/lib/src/retry_timer.dart, clients/client-dart/lib/src/transport.dart, clients/client-dart/lib/src/utils.dart, clients/client-dart/pubspec.lock, clients/client-dart/pubspec.yaml, clients/client-dart/test/async_client_test.dart, clients/client-dart/test/retry_timer_test.dart, clients/client-dart/test/transport_test.dart
=> feat: add DCL and fix issues

.github/workflows/build-client-dart.yaml, clients/client-dart/README.md
- Add build workflow for dart client.
- Fix release workflow
=> feat: add  build workflow

clients/client-dart/.pubignore, clients/client-dart/example/adf_client_example.dart, clients/client-dart/lib/src/async_client.dart, clients/client-dart/lib/src/binary_decoder.dart, clients/client-dart/lib/src/json_decoder.dart, clients/client-dart/test/async_client_test.dart, clients/client-dart/test/binary_decoder_test.dart, clients/client-dart/test/json_decoder_test.dart, clients/client-dart/test/retry_timer_test.dart, clients/client-dart/test/transport_test.dart, clients/client-dart/test/utils_test.dart
=> fix: analyze suggestions

.github/workflows/build-channel-bridge.yaml, README.md, channel-bridge/README.md, channel-bridge/apps/bridge_core/lib/bridge_core.ex, channel-bridge/apps/bridge_core/lib/bridge_core/boundary/channel_manager.ex, channel-bridge/apps/bridge_core/test/bridge_core/boundary/node_observer_test.exs, channel-bridge/apps/bridge_core/test/bridge_core/channel_test.exs, channel-bridge/apps/bridge_core/test/bridge_core_test.exs, channel-bridge/apps/bridge_helper_config/lib/bridge_helper_config/application.ex, channel-bridge/apps/bridge_helper_config/lib/bridge_helper_config/application_config.ex, channel-bridge/apps/bridge_helper_config/test/application_config_test.exs, channel-bridge/apps/bridge_rabbitmq/lib/bridge_rabbitmq/application.ex, channel-bridge/apps/bridge_rabbitmq/test/bridge_rabbitmq/application_test.exs, channel-bridge/apps/bridge_rabbitmq/test/bridge_rabbitmq/subscriber_test.exs, channel-bridge/apps/bridge_restapi/test/bridge_api_test.exs, channel-bridge/apps/bridge_secretmanager/test/bridge_secret_manager/application_test.exs, channel-bridge/config-local.yaml, channel-bridge/config/dev.exs, channel-bridge/data_samples/event_payload_sample.json, channel-bridge/deploy_samples/k8s/libcluster-kubernetes/README.md, channel-bridge/deploy_samples/k8s/libcluster-kubernetes/app.yaml, channel-bridge/deploy_samples/k8s/libcluster-kubernetes/configmap.yaml, channel-bridge/deploy_samples/k8s/libcluster-kubernetes/gateway.yaml, channel-bridge/deploy_samples/k8s/libcluster-kubernetes/namespace.yaml, channel-bridge/deploy_samples/k8s/libcluster-kubernetes/roles.yaml, channel-bridge/docs/channel_authentication.md, channel-bridge/docs/channel_opening.md, channel-bridge/docs/message_routing.md
Added docs, samples and github action
=> feature: add docs, samples and action

.github/workflows/dependabot.yml
=> feat: add dependabot

.github/workflows/release-client-dart.yml
=> fix: release management dart client

.github/workflows/scorecards-analysis.yml
Update scorecard dependencies and apply security best practices
=> fix: update scorecards-analysis.yml

clients/client-dart/CHANGELOG.md, clients/client-dart/lib/src/async_client.dart, clients/client-dart/lib/src/status_codes.dart, clients/client-dart/lib/src/transport.dart, clients/client-dart/pubspec.yaml
- Retry reconnect web socket when the connection was closed unexpected
- Close socket and do not reconnect when disconnect cleanly
=> [dart client] fix: retry reconnect web socket

clients/client-dart/pubspec.yaml
This pull request adds the `flutter` SDK as a dependency in the `pubspec.yaml` file for the Dart client.
=> fix: Update pubspec.yaml

clients/client-dart/example/lib/async_client_service.dart, clients/client-dart/example/lib/infrastructure/async_dataflow/event_handler.dart, clients/client-dart/lib/channel_sender_client.dart, clients/client-dart/lib/src/async_client_conf.dart, clients/client-dart/lib/src/async_client_event_handler.dart, clients/client-dart/lib/src/async_config.dart, clients/client-dart/lib/src/transport/types/sse_transport.dart, clients/client-dart/lib/src/transport/types/ws_transport.dart, clients/client-dart/pubspec.yaml, clients/client-dart/test/async_client_event_handler_test.dart
This pull request introduces an event handling mechanism to improve observability and debugging in the `AsyncClientConf` and `WSTransport` classes. The changes include the addition of an `AsyncClientEventHandler` interface, integration of event handling into various lifecycle and connectivity methods, and updates to the `AsyncConfig` class to support the new event handler.
* **`clients/client-dart/lib/src/async_client_conf.dart`:** Added calls to `_config.eventHandler?.onEvent` in key lifecycle and connectivity methods to dispatch events with detailed messages and `channelRef` information. These events cover connectivity changes, app lifecycle state changes, connection errors, and reconnection attempts. [[1]](diffhunk://#diff-4aa5ccf7c46c7c016782c42016724609121f033815e09254a6fdd47b005ddae1 …
=> feat(dart): add event handler interface
